
plot_labels = {
               'Mnu': r'$\Sigma m_\nu$ [eV]',
               'Om': r'$\Omega_m$',
               'Ob': r'$\Omega_b$',
               'h': r'$h$',
               'ns': r'$n_s$',
               '1e9As': r'$10^9 A_s$',
               'sigma8': r'$\sigma_8$',
               'Oc': r'$\Omega_{\sf cdm}$',
               'On': r'$\Omega_\nu$',
               'S8': r'$S_8$',
               'logA': r'$\log 10^{10} A_s$',
               'theta': r'$\theta_{\sf MC}$',
               'Obh2': r'$\Omega_b h^2$',
               'Och2': r'$\Omega_{\sf cdm} h^2$',
               'hod_transfP1': r'$P_1$',
               'hod_abias': r'$a_{sf bias}$',
               'hod_log_Mmin': r'$\log M_{\sf min}$',
               'hod_sigma_logM': r'$\sigma_{\log M}$',
               'hod_log_M0': r'$\log M_0$',
               'hod_log_M1': r'$\log M_1$',
               'hod_alpha': r'$\alpha$',
               'hod_transf_eta_cen': r'$\eta_{\sf cen}$',
               'hod_transf_eta_sat': r'$\eta_{\sf sat}$',
               'hod_mu_Mmin': r'$\mu(M_{\sf min})$',
               'hod_mu_M1': r'$\mu(M_1)$',
               'eft_b1': r'$b_1$',
               'eft_b2': r'$b_2$',
               'eft_bG2': r'$b_{G2}$',
              }

nounit = lambda s: '$' + s.split('$')[1] + '$'
